language: node_js
node_js:
  - "node"
before_script:
  - npm install -g gatsby-cli
script:
  - npm run lint
  - npm run test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build; fi
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  keep-history: true
  email: 34457519+slohacksbot@users.noreply.github.com
  name: SLO Hacks Bot
  on:
    branch: master
